---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
    ports:
      - "3306:3306"
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /var/lib/mysql

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - nextcloud
    volumes:
      - /path/to/app:/app

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - nextcloud

  nextcloud-server:
    build: .
    links:
      - mariadb
    volumes:
      - /opt/nextcloud
    environment:
      - DATABASE_HOST=mariadb
      - URL=https://127.0.0.1
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - mariadb
      - phpfpm
      - redis
    networks:
      - nextcloud
    restart: on-failure # Added this to give maria_db to configure for testing purposes
    healthcheck:
      test: ["CMD", "ansible-playbook", "upstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nextcloud:
    driver: bridge
