---
version: "2.4"
services:
  mariadb:
    image: 'mariadb:latest'
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
    ports:
      - "3306:3306"
    networks:
      - nextcloud

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    networks:
      - nextcloud
  nextcloud:
    image: penguincloud/nextcloud
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb
      - redis
    networks:
      - nextcloud
    healthcheck:
      test: ["CMD", "ansible-playbook", "upstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nextcloud:
