---
- name: Nextcloud
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
    - vars/apps.yml
  tasks:
    - name: Build Actions
      tags:
        - build
      block:
        - name: Install Nextcloud Dependencies
          ansible.builtin.include_tasks:
            file: jobs/build/install_dependancies.yml
            apply:
              tags:
                - build

        - name: Install Nextcloud
          ansible.builtin.include_tasks:
            file: jobs/build/install_nextcloud.yml
            apply:
              tags:
                - build
        - name: set permissions for nginx
          ansible.builtin.include_tasks:
            file: jobs/build/permissions_nginx.yml
            apply:
              tags:
                - build
        - name: Set permissions for php-fpm
          ansible.builtin.include_tasks:
            file: jobs/build/6permissions_phpfpm.yml
            apply:
              tags:
                - build
        - name: Create open ssl certificate repo's
          ansible.builtin.include_tasks:
            file: jobs/build/create_cert_directories.yml
            apply:
              tags:
                - build
    - name: Run Actions
      tags:
        - run
      block:
        - name: Generate SSL certificate
          ansible.builtin.include_tasks:
            file: jobs/run/ssl_generate.yml
            apply:
              tags:
                - run
          when: ssl_cert == "open"

        - name: Configure PHP_FPM
          ansible.builtin.include_tasks:
            file: config_phpfpm.yml
            apply:
              tags:
                - run
        - name: Configure NGINX
          ansible.builtin.include_tasks:
            file: jobs/run/config_nginx.yml
            apply:
              tags:
                - run
        - name: Test database
          ansible.builtin.include_tasks:
            file: jobs/tests/database_test.yml
            apply:
              tags:
                - run
        - name: Configure nextcloud.yml
          ansible.builtin.include_tasks:
            file: jobs/run/config_nextcloud.yml
            apply:
              tags:
                - run
        - name: Install apps
          ansible.builtin.include_tasks:
            file: jobs/run/apps_nextcloud.yml
            apply:
              tags:
                - run
        - name: Test Nginx
          ansible.builtin.include_tasks:
            file: jobs/tests/test_nginx.yml
            apply:
              tags:
                - run
