---
- hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  become: true
  become_user: root
  remote_user: root
  tasks:
    - name: Include nodeType variables
      include_vars:
        file: "vars/base9.yml"
      tags:
        - always
      ignore_errors: true
    - name: Build And Install
      include_tasks:
        file: jobs/build/build.yml
        apply:
          tags:
            - build
      tags:
        - build
    - name: Run Configuration and Live
      include_tasks:
        file: jobs/run/run.yml
        apply:
          tags:
            - run
      tags:
        - run
    - name: Test database connectivity
      include_tasks:
        file: jobs/tests/database_test.yml
        apply:
          tags:
            - database_connectivity
            - test
            - run
      tags:
        - database_connectivity
        - test
        - run
    - name: Configure nextcloud for start up
      include_tasks:
        file: jobs/run/config_nextcloud.yml
        apply:
          tags:
            - config-nextcloud
            - run
      tags:
        - config_nextcloud
        - run
#   Only after nextcloud is installed can the apps be installed
    - name: Install nextcloud apps
      include_tasks:
        file: jobs/run/apps_nextcloud.yml
        apply:
          tags:
            - app_install
            - run
      tags:
        - app_install
        - run
    - name: Run tests to make sure build and run applied application correctly
      include_tasks:
        file: jobs/tests/test.yml
        apply:
          tags:
            - run
            - test
      tags:
        - run
        - test
    - name: Execute application
      include_tasks:
        file: jobs/exec/exec.yml
        apply:
          tags:
            - exec
      tags:
        - exec
