---
run:
  user: www-data
app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE') }}"
  link: "{{ lookup('env', 'APP_LINK') }}"
  version: "{{ lookup('env', 'APP_VERSION') }}"
database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"
  type: "{{ lookup('env', 'DATABASE_TYPE') }}"
organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"
redis:
  host: "{{ lookup('env', 'REDIS_HOST') }}"
  port: "{{ lookup('env', 'REDIS_PORT') }}"
  password: "{{ lookup('env', 'REDIS_PASS') }}"
  timeout: "{{ lookup('env', 'REDIS_TIMEOUT') }}"
admin:
  logging: "{{ lookup('env', 'ADMIN_LOGGING') }}"
  password: "{{ lookup('env', 'ADMIN_PASS') }}"
url: "{{ lookup('env', 'URL') }}"
trusted_domain: "{{ lookup('env', 'TRUSTED_DOMAIN') }}"
cpu_count: "{{ lookup('env', 'CPU_COUNT') }}"
file_limit: "{{ lookup('env', 'FILE_LIMIT') }}"
app_link: "{{ lookup('env', 'APP_LINK') }}"
ports:
  http: "{{ lookup('env', 'HTTP_PORT') }}"
  https: "{{ lookup('env', 'HTTPS_PORT') }}"
server_address: "{{ lookup('env', 'SERVER_ADDRESS') }}"
ssl_cert: "{{ lookup('env', 'SSL_CERT') }}"
protocol: "{{ lookup('env', 'PROTOCOL') }}"
test_ports:
  - 8080
  - 8443
