---
database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"

organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"

redis:
  host: "{{ lookup('env', 'REDIS_HOST') }}"
  port: "{{ lookup('env', 'REDIS_PORT') }}"
  password: "{{ lookup('env', 'REDIS_PASS') }}"
  timeout: "{{ lookup('env', 'REDIS_TIMEOUT') }}"

admin:
  logging: "{{ lookup('env', 'ADMIN_LOGGING') }}"
  password: "{{ lookup('env', 'ADMIN_PASS') }}"

url: "{{ lookup('env', 'URL') }}"

trusted_domain:  "{{ lookup('env', 'TRUSTED_DOMAIN') }}"

cpu_count: "{{ lookup('env', 'CPU_COUNT') }}"

file_limit: "{{ lookup('env', 'FILE_LIMIT') }}"

app_link: "{{ lookup('env', 'APP_LINK') }}"

apps:
  - polls
  - forms
  - mail
  - onlyoffice
  - appointments
  - passman
  - spreed
  - solid

nextcloud_apps:
  - https://github.com/nextcloud/polls/releases/download/v3.4.0-beta1/polls.tar.gz
  - https://github.com/nextcloud-releases/forms/releases/download/v2.4.0/forms-v2.4.0.tar.gz
  - https://github.com/nextcloud-releases/mail/releases/download/v1.11.4/mail-v1.11.4.tar.gz
  - https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v7.2.1/onlyoffice.tar.gz
  - https://github.com/SergeyMosin/Appointments/raw/82836bdefb36676d7f256571f2f5dd64d4635eed/build/artifacts/appstore/appointments.tar.gz
  - https://releases.passman.cc/passman_2.4.0.tar.gz
  - https://github.com/nextcloud-releases/spreed/releases/download/v13.0.0-rc.4/spreed-v13.0.0-rc.4.tar.gz
  - https://github.com/pdsinterop/solid-nextcloud/releases/download/v0.4.2/solid.tar.gz
