---
- name: Delete sample.config file
  file:
    path: /opt/nextcloud/config/config.sample.php
    state: absent

- name: Template autoconfig to opt/nextcloud/config
  template:
    src: templates/nextcloud_autoconfig.j2
    dest: /opt/nextcloud/config/autoconfig.php