---
- name: Check if config file exsists
  stat:
    path: /opt/nextcloud/config/config.php
  register: result

- name: Run occ installation command
  command: >
    php occ maintenance:install
    --database={{ database.type}}
    --database-host={{ database.host }}
    --database-name={{ database.name }}
    --database-user={{ database.user }}
    --database-pass={{ database.password }}
    --admin-user={{ admin.logging }}
    --admin-pass={{ admin.password }}
  args:
    chdir: /opt/nextcloud
  when: result.stat.exists == False
- name: Run OCC to set redis
  command: >
    php occ config:system:set redis host --value={{ redis.host }}
    php occ config:system:set redis port --value={{ redis.port }}
    php occ config:system:set redis password --value={{ redis.password }}
    php occ config:system:set redis timeout --value={{ redis.timeout }}
  args:
    chdir: /opt/nextcloud
