---
- name: Template php-fpm www config file
  ansible.builtin.template:
    src: /opt/manager/templates/www_config.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf
    force: true
    owner: www-data
    backup: true
